services:
  db:
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: StrongPassword01
      POSTGRES_DB: RoomEditor         # <--- Создаст нужную базу
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# https://dockerhosting.ru/blog/postgresql-v-docker/

# http://127.0.0.1:8081